name: Lint and Format
on: [push]
jobs:
    install-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install
            - name: Linter
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: lint
